slice_name: Total Rides From Top 15 Start Stations (Members)
viz_type: dist_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: member
    expressionType: SIMPLE
    filterOptionName: filter_nzv6gulysyq_wijcwac5wvo
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: member_casual
  bottom_margin: auto
  color_scheme: d3Category20c
  columns:
  - member_casual
  datasource: 35__table
  extra_form_data: {}
  groupby:
  - start_station_name
  metrics:
  - aggregate: MAX
    column:
      certification_details: null
      certified_by: null
      column_name: total_rides
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 932
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(18, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: MAX(total_rides)
    optionName: metric_wdau5ih72m8_ncmgu2duer9
    sqlExpression: null
  order_desc: true
  rich_tooltip: true
  row_limit: '15'
  show_bar_value: true
  show_legend: false
  slice_id: 114
  time_range: No filter
  timeseries_limit_metric: []
  viz_type: dist_bar
  x_axis_label: ''
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: a4509f10-b0e5-47c9-846e-d4eb02ee24a7
version: 1.0.0
dataset_uuid: 67eedb62-a7a2-410b-b5ba-e7a468242ca7
