slice_name: Total Rides Grouped By Different Start/End Stations (Top 500)
viz_type: table
params:
  adhoc_filters: []
  all_columns:
  - TOTAL_FROM
  - START_STATION_NAME
  - END_STATION_NAME
  color_pn: true
  conditional_formatting: []
  datasource: 29__table
  extra_form_data: {}
  groupby: []
  include_search: true
  order_by_cols:
  - '["TOTAL_FROM", false]'
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 112
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  viz_type: table
cache_timeout: null
uuid: 1a7ddc65-0903-4c31-81b6-8189650533ac
version: 1.0.0
dataset_uuid: 3755dc74-6734-4b9e-9b55-5e2088e7b9be
